
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/just-life-db?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never